# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-12 19:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('level', models.CharField(choices=[(b'EMERG', b'EMERG'), (b'ALERT', b'ALERT'), (b'CRIT', b'CRIT'), (b'ERR', b'ERR'), (b'WARNING', b'WARNING'), (b'NOTICE', b'NOTICE'), (b'INFO', b'INFO'), (b'DEBUG', b'DEBUG')], max_length=8)),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
